### ISSUE TITLE
Compilation errors are not caught

### ISSUE THREAD

**Issue by Witiko** [Witiko/lt3luabridge#18]
While the lt3luabridge library catches execution errors, it fails to catch compilation errors. We can catch compilation errors by explicitly using the `load()` function to compile Lua chunks rather than executing the Lua chunks directly and hoping for the best.

**Comment by Witiko** [comment]
### Tasks

- [ ] Escape `\` and `"` in `\l_tmpa_tl`:
  https://github.com/Witiko/lt3luabridge/blob/6917725d7c09e17b034daf7cc293d79fcd8432d4/lt3luabridge.dtx#L298-L300
  https://github.com/Witiko/lt3luabridge/blob/6917725d7c09e17b034daf7cc293d79fcd8432d4/lt3luabridge.dtx#L415-L417
- [ ] Replace `local error` with `local err`.
  https://github.com/Witiko/lt3luabridge/blob/6917725d7c09e17b034daf7cc293d79fcd8432d4/lt3luabridge.dtx#L304
  https://github.com/Witiko/lt3luabridge/blob/6917725d7c09e17b034daf7cc293d79fcd8432d4/lt3luabridge.dtx#L316
- [ ] Replace `\exp_not:V \l_tmpa_tl` with `ran_ok, err = load(" \exp_not:V \l_tmpa_tl ")` and `if~not~ran_ok~then~error(err) end~`
  https://github.com/Witiko/lt3luabridge/blob/6917725d7c09e17b034daf7cc293d79fcd8432d4/lt3luabridge.dtx#L304-L309
  https://github.com/Witiko/lt3luabridge/blob/6917725d7c09e17b034daf7cc293d79fcd8432d4/lt3luabridge.dtx#L433
